#!/usr/bin/env python3
"""
forge-sdd - CLI for Specification-Driven Development toolkit

Usage:
    forge-sdd init <project-name>
"""

import sys
import os
import shutil
from pathlib import Path
from datetime import datetime


def print_header():
    print("\n🚀 forge-sdd-toolkit initializer\n")


def print_success(message):
    print(f"✅ {message}")


def print_error(message):
    print(f"❌ {message}", file=sys.stderr)


def print_step(message):
    print(f"⏳ {message}...", end="", flush=True)


def print_step_done():
    print(" ✅")


def get_toolkit_root():
    """Get the root directory of the installed toolkit"""
    # When installed via uv/pip, this module is in site-packages/forge_sdd_toolkit/
    # The structure/ directory should be in site-packages/forge_sdd_toolkit/structure/
    module_dir = Path(__file__).parent.absolute()
    
    # Try different possible locations
    possible_roots = [
        # When installed via uv/pip with shared-data
        module_dir.parent / "forge_sdd_toolkit",
        # When running from development
        module_dir.parent.parent.parent,
        # Direct reference to module dir (structure inside package)
        module_dir,
    ]
    
    for root in possible_roots:
        structure_path = root / "structure"
        if structure_path.exists() and (structure_path / "prompts" / "commands").exists():
            return root
    
    # If not found, raise error with helpful message
    raise FileNotFoundError(
        "Could not find toolkit structure files. "
        "This usually means the package was not installed correctly. "
        f"Tried: {[str(p) for p in possible_roots]}"
    )


def transform_paths(content):
    """Transform relative paths from toolkit structure to user project structure"""
    # Base prompts: ../base/ → _base/
    content = content.replace("../base/", "_base/")
    content = content.replace("../../prompts/base/", "_base/")
    
    # Templates: ../../templates/ → ../.forge-sdd/templates/
    content = content.replace("../../templates/", "../.forge-sdd/templates/")
    content = content.replace("../templates/", "../.forge-sdd/templates/")
    
    # Schemas: ../../schemas/ → ../.forge-sdd/schemas/
    content = content.replace("../../schemas/", "../.forge-sdd/schemas/")
    content = content.replace("../schemas/", "../.forge-sdd/schemas/")
    
    # Docs: ../../docs/ → ../docs/
    content = content.replace("../../docs/", "../docs/")
    
    return content


def add_generation_header(content, source_path):
    """Add auto-generation header to file"""
    timestamp = datetime.now().isoformat()
    header = f"""<!--
🤖 AUTO-GENERATED by forge-sdd-toolkit
📄 Source: {source_path}
📅 Generated: {timestamp}

⚠️  DO NOT EDIT THIS FILE MANUALLY
💡 To update: Run `forge-sdd update`

This file is part of the SDD (Specification-Driven Development) lifecycle.
Learn more: https://github.com/4youtest-vsalmeida/forge-sdd-toolkit
-->

"""
    return header + content


def copy_with_transform(src, dest, transform=False, add_header=False, source_path=""):
    """Copy file with optional path transformation and header"""
    dest.parent.mkdir(parents=True, exist_ok=True)
    
    if not transform and not add_header:
        shutil.copy2(src, dest)
        return
    
    with open(src, 'r', encoding='utf-8') as f:
        content = f.read()
    
    if transform:
        content = transform_paths(content)
    
    if add_header:
        content = add_generation_header(content, source_path)
    
    with open(dest, 'w', encoding='utf-8') as f:
        f.write(content)


def copy_directory(src, dest):
    """Recursively copy directory"""
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest)


def init_project(project_name):
    """Initialize a new SDD project"""
    print_header()
    
    # Validate project name
    if not project_name or not project_name.replace('-', '').replace('_', '').isalnum():
        print_error("Project name must contain only letters, numbers, hyphens, and underscores")
        sys.exit(1)
    
    # Get paths
    toolkit_root = get_toolkit_root()
    project_path = Path.cwd() / project_name
    
    # Check if project already exists
    if project_path.exists():
        print_error(f"Directory '{project_name}' already exists")
        sys.exit(1)
    
    try:
        # Step 1: Create directory structure
        print_step("Creating project structure")
        project_path.mkdir(parents=True)
        (project_path / ".github" / "prompts" / "_base").mkdir(parents=True)
        (project_path / ".forge-sdd" / "templates").mkdir(parents=True)
        (project_path / ".forge-sdd" / "schemas").mkdir(parents=True)
        (project_path / "docs").mkdir(parents=True)
        (project_path / ".vscode").mkdir(parents=True)
        print_step_done()
        
        # Step 2: Copy GitHub Copilot prompts (stage prompts)
        print_step("Setting up GitHub Copilot prompts")
        prompts_source = toolkit_root / "structure" / "prompts" / "commands"
        stage_prompts = [
            "forge-ideate.md",
            "forge-architect.md",
            "forge-plan.md",
            "forge-implement.md",
            "forge-test.md",
            "forge-operate.md"
        ]
        
        for filename in stage_prompts:
            src = prompts_source / filename
            if src.exists():
                dest = project_path / ".github" / "prompts" / filename.replace(".md", ".prompt.md")
                copy_with_transform(
                    src, dest,
                    transform=True,
                    add_header=True,
                    source_path=f"structure/prompts/commands/{filename}"
                )
        
        # Copy base prompts
        base_source = toolkit_root / "structure" / "prompts" / "base"
        base_prompts = ["system-prompt.md", "decision-framework.md"]
        
        for filename in base_prompts:
            src = base_source / filename
            if src.exists():
                dest = project_path / ".github" / "prompts" / "_base" / filename
                copy_with_transform(
                    src, dest,
                    transform=True,
                    add_header=True,
                    source_path=f"structure/prompts/base/{filename}"
                )
        
        print_step_done()
        
        # Step 3: Copy templates
        print_step("Copying SDD templates")
        templates_source = toolkit_root / "structure" / "templates"
        templates_dest = project_path / ".forge-sdd" / "templates"
        if templates_source.exists():
            copy_directory(templates_source, templates_dest)
        print_step_done()
        
        # Step 4: Copy schemas
        print_step("Copying validation schemas")
        schemas_source = toolkit_root / "structure" / "schemas"
        schemas_dest = project_path / ".forge-sdd" / "schemas"
        if schemas_source.exists():
            copy_directory(schemas_source, schemas_dest)
        print_step_done()
        
        # Step 5: Generate project files
        print_step("Generating project files")
        
        # README.md
        readme_content = f"""# {project_name}

> Generated by [forge-sdd-toolkit](https://github.com/4youtest-vsalmeida/forge-sdd-toolkit)

## Quick Start

1. Open this project in VS Code
2. Open GitHub Copilot Chat (Cmd/Ctrl + I)
3. Type: `@forge-ideate`
4. Describe your Forge app idea
5. Follow the 6-stage SDD lifecycle

## The 6-Stage SDD Lifecycle

```
IDEATE → ARCHITECT → PLAN → IMPLEMENT → TEST → OPERATE
```

### 1. IDEATE → Specification
```bash
@forge-ideate
I want to build a Jira app that shows GitHub PR status in issue panels
```
**Output**: `docs/specification-document.md`

### 2. ARCHITECT → Architecture Decisions
```bash
@forge-architect
[Copilot reads specification and makes technical decisions]
```
**Output**: `docs/ADD.md`

### 3. PLAN → Implementation Plan
```bash
@forge-plan
[Copilot breaks down architecture into tasks]
```
**Output**: `docs/implementation-plan.md`

### 4. IMPLEMENT → Working Code
```bash
@forge-implement
[Copilot generates production-ready code]
```
**Output**: Source code, `manifest.yml`, `package.json`

### 5. TEST → Test Suite
```bash
@forge-test
[Copilot generates comprehensive tests]
```
**Output**: Test files

### 6. OPERATE → Deployment
```bash
@forge-operate
[Copilot sets up CI/CD and monitoring]
```
**Output**: Deployment configs

## Learn More

- [SDD Methodology](https://github.com/4youtest-vsalmeida/forge-sdd-toolkit#readme)
- [Forge Platform Docs](https://developer.atlassian.com/platform/forge/)
- [GitHub Copilot](https://github.com/features/copilot)

---

**Built with ❤️ using SDD**
"""
        
        with open(project_path / "README.md", 'w') as f:
            f.write(readme_content)
        
        # .gitignore
        gitignore_content = """# SDD temporary files
*.draft.md
*.tmp.md
*.wip.md

# Node modules
node_modules/

# Forge
.forge/
.tunnel/
build/
dist/

# OS
.DS_Store
Thumbs.db

# IDE
.vscode/*
!.vscode/settings.json
.idea/

# Logs
*.log
npm-debug.log*
"""
        
        with open(project_path / ".gitignore", 'w') as f:
            f.write(gitignore_content)
        
        # .vscode/settings.json
        vscode_settings = """{
  "github.copilot.enable": {
    "*": true,
    "yaml": true,
    "markdown": true
  },
  "files.associations": {
    "*.prompt.md": "markdown"
  }
}
"""
        
        with open(project_path / ".vscode" / "settings.json", 'w') as f:
            f.write(vscode_settings)
        
        print_step_done()
        
        # Success!
        print(f"\n✅ Project '{project_name}' initialized successfully!\n")
        print("📋 Next Steps:\n")
        print(f"  1. cd {project_name}")
        print("  2. code .")
        print("  3. Open GitHub Copilot Chat")
        print("  4. Type: @forge-ideate")
        print("  5. Describe your app idea\n")
        
    except Exception as e:
        print_error(f"Failed to initialize project: {str(e)}")
        # Cleanup on error
        if project_path.exists():
            shutil.rmtree(project_path)
        sys.exit(1)


def show_help():
    """Show help message"""
    print("""
forge-sdd - Specification-Driven Development toolkit for Atlassian Forge apps

Usage:
    forge-sdd init <project-name>     Initialize a new SDD project
    forge-sdd install                 Show installation instructions
    forge-sdd --help                  Show this help message
    forge-sdd --version               Show version information

Examples:
    forge-sdd init my-forge-app       Create a new project
    forge-sdd install                 Get installation help

Learn more: https://github.com/4youtest-vsalmeida/forge-sdd-toolkit
""")


def show_version():
    """Show version information"""
    from . import __version__
    print(f"forge-sdd-toolkit version {__version__}")


def show_install_help():
    """Show installation instructions"""
    print("""
🚀 forge-sdd-toolkit Installation Guide

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📦 Recommended: Install via uv (Fast! ⚡)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   # Install from GitHub
   uv tool install git+https://github.com/4youtest-vsalmeida/forge-sdd-toolkit

   # Install from local directory (development)
   uv tool install --editable .

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📦 Alternative: Install via pip
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   # Install from GitHub
   pip install git+https://github.com/4youtest-vsalmeida/forge-sdd-toolkit

   # Install from local directory (development)
   pip install --editable .

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔧 For Development
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   # Clone and install in editable mode
   git clone https://github.com/4youtest-vsalmeida/forge-sdd-toolkit.git
   cd forge-sdd-toolkit
   uv tool install --editable .

   # Now you can edit the code and changes will be reflected immediately!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📚 Next Steps
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   forge-sdd init my-forge-app
   cd my-forge-app
   code .

   Then open GitHub Copilot and type: @forge-ideate

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
""")


def main():
    """Main CLI entry point"""
    if len(sys.argv) < 2:
        show_help()
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command in ["--help", "-h", "help"]:
        show_help()
    
    elif command in ["--version", "-v", "version"]:
        show_version()
    
    elif command == "install":
        show_install_help()
    
    elif command == "init":
        if len(sys.argv) < 3:
            print_error("Project name required")
            print("Usage: forge-sdd init <project-name>")
            sys.exit(1)
        
        project_name = sys.argv[2]
        init_project(project_name)
    
    else:
        print_error(f"Unknown command: {command}")
        show_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
